language: android
jdk: oraclejdk8
group: edge

android:
  components:
    - tools
    - build-tools-24.0.3
    - android-24
    - platform-tools
    - extra-android-m2repository


env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

script:
  - ./gradlew build assembleAndroidTest